name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          entrypoint: ./build.sh
      - name: Publish PDF
        uses: actions/upload-artifact@v4
        with:
          name: worksheets
          path: macropad/worksheet/worksheet.pdf
